-- V11: Demo stage history — the initial "job opened" row for every seeded job,
-- plus the real Stage Change Log entries transcribed from the workbook (marked
-- 'Seeded' there too — the workbook itself notes these are reconstructed
-- estimates for the sample data, not live-logged events).

-- Initial NOT_STARTED entry for every seeded job (from_stage_id NULL = job creation).
INSERT INTO fabrication_stage_history (job_id, from_stage_id, to_stage_id, changed_at, days_held, changed_by_user_id, is_correction, note)
SELECT j.id, NULL, (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), j.job_card_date, 0,
       (SELECT id FROM users WHERE username='admin'), FALSE, 'Job card opened'
FROM fabrication_jobs j;

-- Helper note: (job_id via vehicle_id subquery, from/to via code subquery, admin as actor)
INSERT INTO fabrication_stage_history (job_id, from_stage_id, to_stage_id, changed_at, days_held, changed_by_user_id, is_correction, note) VALUES
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-006'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-07-24 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-006'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-07-29 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-005'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-08-03 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-006'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-08-05 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-005'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-08-08 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-006'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-08-12 00:00:00', 14, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-006'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-08-13 00:00:00', 20, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-006'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-08-17 00:00:00', 12, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-005'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-08-18 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-005'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-08-21 00:00:00', 18, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-005'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-08-22 00:00:00', 14, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-004'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-08-23 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-004'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-08-25 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-005'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-08-28 00:00:00', 10, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-004'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-08-31 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-003'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-09-02 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-003'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-09-04 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-004'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-09-04 00:00:00', 12, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-004'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-09-06 00:00:00', 12, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-003'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-09-10 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-005'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), '2026-09-14 00:00:00', 24, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-004'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-09-14 00:00:00', 14, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-002'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-09-15 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-005'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), '2026-09-16 00:00:00', 25, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-002'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-09-17 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-005'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), '2026-09-17 00:00:00', 20, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-003'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-09-18 00:00:00', 14, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-006'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), '2026-09-18 00:00:00', 36, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-002'), (SELECT id FROM fabrication_stages WHERE code='NOT_STARTED'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), '2026-09-18 00:00:00', 0, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-006'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), '2026-09-19 00:00:00', 38, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-006'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), (SELECT id FROM fabrication_stages WHERE code='RELEASED'), '2026-09-19 00:00:00', 1, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-004'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), '2026-09-20 00:00:00', 14, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TK-006'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), (SELECT id FROM fabrication_stages WHERE code='RELEASED'), '2026-09-20 00:00:00', 1, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-003'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-09-20 00:00:00', 18, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='BS-004'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), '2026-09-20 00:00:00', 16, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-003'), (SELECT id FROM fabrication_stages WHERE code='IN_PRODUCTION'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), '2026-09-20 00:00:00', 10, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-006'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), '2026-09-20 00:00:00', 34, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-004'), (SELECT id FROM fabrication_stages WHERE code='AT_FINISHING'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), '2026-09-21 00:00:00', 7, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded'),
((SELECT id FROM fabrication_jobs WHERE vehicle_id='TP-006'), (SELECT id FROM fabrication_stages WHERE code='AT_DELIVERY_STORE'), (SELECT id FROM fabrication_stages WHERE code='RELEASED'), '2026-09-21 00:00:00', 1, (SELECT id FROM users WHERE username='admin'), FALSE, 'Seeded');
